import React, { useEffect, useMemo, useState } from 'react';
import { FiActivity, FiAlertTriangle, FiCalendar, FiCheckCircle, FiRefreshCw, FiTrendingUp } from 'react-icons/fi';
import { getProgressReading } from '../utils/projectProgress';
import '../styles/AgentMonitor.css';

const API_URL = 'http://localhost:5000/api/agent';

function MetricCard({ icon, label, value, tone = 'blue' }) {
  return (
    <div className={`agent-metric agent-metric-${tone}`}>
      <div className="agent-metric-icon">{icon}</div>
      <div>
        <div className="agent-metric-value">{value}</div>
        <div className="agent-metric-label">{label}</div>
      </div>
    </div>
  );
}

function SignalList({ title, items, getText, emptyText }) {
  return (
    <section className="agent-panel">
      <div className="agent-panel-header">
        <h2>{title}</h2>
        <span>{items.length}</span>
      </div>
      {items.length > 0 ? (
        <div className="agent-signal-list">
          {items.slice(0, 8).map((item, index) => (
            <div className="agent-signal-item" key={`${title}-${item.id || index}`}>
              {getText(item)}
            </div>
          ))}
        </div>
      ) : (
        <p className="agent-empty">{emptyText}</p>
      )}
    </section>
  );
}

export default function AgentMonitor() {
  const [latestReport, setLatestReport] = useState(null);
  const [snapshot, setSnapshot] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  const report = latestReport?.report;
  const metrics = report?.metrics || snapshot?.metrics;
  const signals = report?.signals || snapshot?.signals;

  const generatedAt = useMemo(() => {
    const value = report?.generatedAt || latestReport?.created_at;
    if (!value) return 'No report yet';
    return new Date(value).toLocaleString();
  }, [report, latestReport]);

  useEffect(() => {
    fetchAgentData();
  }, []);

  async function fetchAgentData() {
    setError('');
    setLoading(true);

    try {
      const [latestRes, snapshotRes, historyRes] = await Promise.all([
        fetch(`${API_URL}/latest`),
        fetch(`${API_URL}/snapshot`),
        fetch(`${API_URL}/reports?limit=7`)
      ]);

      if (latestRes.ok) {
        setLatestReport(await latestRes.json());
      } else if (latestRes.status !== 404) {
        throw new Error('Unable to load the latest agent report');
      }

      if (!snapshotRes.ok) {
        throw new Error('Unable to load the live system snapshot');
      }

      if (!historyRes.ok) {
        throw new Error('Unable to load agent history');
      }

      setSnapshot(await snapshotRes.json());
      setHistory(await historyRes.json());
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function generateReport() {
    setGenerating(true);
    setError('');

    try {
      const response = await fetch(`${API_URL}/daily-update`, { method: 'POST' });
      if (!response.ok) {
        throw new Error('Unable to generate daily monitoring update');
      }
      await fetchAgentData();
    } catch (err) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }

  if (loading) {
    return <div className="agent-loading">Loading AI monitoring agent...</div>;
  }

  return (
    <div className="agent-monitor">
      <header className="agent-header">
        <div>
          <p className="agent-kicker">Daily monitoring agent</p>
          <h1>Nduna AI System Monitor</h1>
          <p>Automated daily updates across projects, team capacity, milestones, risks, and stale work.</p>
        </div>
        <button className="agent-action" onClick={generateReport} disabled={generating}>
          <FiRefreshCw />
          {generating ? 'Generating...' : 'Generate update'}
        </button>
      </header>

      {error && <div className="agent-error">{error}</div>}

      <div className="agent-status-band">
        <div>
          <span>Latest report</span>
          <strong>{generatedAt}</strong>
        </div>
        <div>
          <span>Generated by</span>
          <strong>{report?.generatedBy || latestReport?.generated_by || 'system-fallback'}</strong>
        </div>
        <div>
          <span>Schedule</span>
          <strong>Daily when ENABLE_DAILY_AGENT=true</strong>
        </div>
      </div>

      <section className="agent-summary">
        <div className="agent-summary-heading">
          <FiActivity />
          <h2>Executive Update</h2>
        </div>
        <pre>{report?.summary || 'No report has been generated yet. Use Generate update to create the first monitoring summary.'}</pre>
      </section>

      {metrics && (
        <div className="agent-metrics-grid">
          <MetricCard icon={<FiTrendingUp />} label="Projects" value={metrics.totals.projects} />
          <MetricCard icon={<FiCheckCircle />} label="Completed" value={metrics.totals.completedProjects} tone="green" />
          <MetricCard icon={<FiActivity />} label="Average progress" value={`${metrics.health.averageProgress}%`} tone="blue" />
          <MetricCard icon={<FiAlertTriangle />} label="Open risks" value={metrics.health.openRisks} tone="amber" />
          <MetricCard icon={<FiCalendar />} label="Overdue milestones" value={metrics.health.overdueMilestones} tone="red" />
          <MetricCard icon={<FiRefreshCw />} label="Stale projects" value={metrics.health.staleProjects} tone="gray" />
        </div>
      )}

      {signals && (
        <div className="agent-panels-grid">
          <SignalList
            title="At-risk projects"
            items={signals.atRiskProjects || []}
            emptyText="No at-risk projects detected."
            getText={(project) => `${project.name} - ${project.status} - ${getProgressReading(project).label}`}
          />
          <SignalList
            title="Overdue milestones"
            items={signals.overdueMilestones || []}
            emptyText="No overdue milestones detected."
            getText={(milestone) => `${milestone.project_name || 'Project'} - ${milestone.title}`}
          />
          <SignalList
            title="Due soon"
            items={signals.dueSoonMilestones || []}
            emptyText="No milestones due in the next 7 days."
            getText={(milestone) => `${milestone.project_name || 'Project'} - ${milestone.title} - ${milestone.due_date || 'No due date'}`}
          />
          <SignalList
            title="Open risks"
            items={signals.openRisks || []}
            emptyText="No open risks detected."
            getText={(risk) => `${risk.severity || 'Medium'} - ${risk.project_name || 'Project'} - ${risk.title}`}
          />
        </div>
      )}

      <section className="agent-history">
        <h2>Report History</h2>
        {history.length > 0 ? (
          <div className="agent-history-list">
            {history.map((item) => (
              <article key={item.id} className="agent-history-item">
                <div>
                  <strong>{item.report_date}</strong>
                  <span>{item.generated_by}</span>
                </div>
                <p>{item.summary}</p>
              </article>
            ))}
          </div>
        ) : (
          <p className="agent-empty">No previous reports yet.</p>
        )}
      </section>
    </div>
  );
}
